import { Brands, Prisma, Stock, Type, TypeOf } from "@prisma/client";

export const PRODUCTS: Prisma.ProductCreateInput[] = [
  {
    title: "Сплит-система Ballu X1200/XS1200",
    description:
      "Энергоэффективная сплит-система для помещений средней площади.",
    brand: Brands.BALLU,
    serie: "Plus",
    images: ["/uploads/ballu1.png", "/uploads/ballu2.png"],
    price: 48990,
    stock: Stock.IN_STOCK,
    type: Type.AIR_CONDITIONER,
    typeOf: TypeOf.WALL_MOUNTED_AIR,
    href: "/products/ballu-x1200",
    groupId: "BALLU-PLUS-1200",
    // airConditionerStat: {
    //   create: {
    //     coolingCapacity: 3.5,
    //     heatingCapacity: 3.7,
    //     areaCoverage: 35,
    //     energyEfficiency: "A++",
    //     noiseLevelIndoor: 24,
    //     noiseLevelOutdoor: 52,
    //     powerConsumption: 1.1,
    //     refrigerantType: "R32",
    //     dimensionsIndoor: "790×275×200",
    //     dimensionsOutdoor: "780×540×250",
    //     weightIndoor: 9.5,
    //     weightOutdoor: 29.0,
    //     inverter: true,
    //     wifi: true,
    //   },
    // },
  },
  {
    title: "Кассетный кондиционер Mitsubishi Electric MXZ-KJ50VA",
    description: "Кассетная модель для офисных помещений.",
    brand: Brands.MITSUBISHI_ELECTRIC,
    serie: "Pro",
    images: ["/uploads/mitsu1.png"],
    price: 96500,
    stock: Stock.PRE_ORDER,
    type: Type.AIR_CONDITIONER,
    typeOf: TypeOf.CASSETE_CONDITIONER,
    href: "/products/mitsu-mxz-kj50va",
    groupId: "MITSUBISHI-PRO-KJ50",
    // airConditionerStat: {
    //   create: {
    //     coolingCapacity: 5.0,
    //     heatingCapacity: 5.6,
    //     areaCoverage: 55,
    //     energyEfficiency: "A+",
    //     noiseLevelIndoor: 29,
    //     noiseLevelOutdoor: 56,
    //     powerConsumption: 1.8,
    //     refrigerantType: "R410A",
    //     dimensionsIndoor: "840×280×840",
    //     dimensionsOutdoor: "880×650×310",
    //     weightIndoor: 22,
    //     weightOutdoor: 45,
    //     inverter: true,
    //     wifi: false,
    //   },
    // },
  },
  {
    title: "Канальный кондиционер Hisense AUD-36HX4SHH",
    description: "Канальный кондиционер для больших помещений.",
    brand: Brands.HISENSE,
    serie: "Premium",
    images: ["/uploads/hisense1.png", "/uploads/hisense2.png"],
    price: 125000,
    stock: Stock.IN_STOCK,
    type: Type.AIR_CONDITIONER,
    typeOf: TypeOf.DUCTED_CONDITIONER,
    href: "/products/hisense-aud36hx4",
    groupId: "HISENSE-PREM-36",
    // airConditionerStat: {
    //   create: {
    //     coolingCapacity: 10.5,
    //     heatingCapacity: 11.2,
    //     areaCoverage: 100,
    //     energyEfficiency: "A",
    //     noiseLevelIndoor: 35,
    //     noiseLevelOutdoor: 58,
    //     powerConsumption: 3.5,
    //     refrigerantType: "R410A",
    //     dimensionsIndoor: "1200×300×700",
    //     dimensionsOutdoor: "950×900×400",
    //     weightIndoor: 38,
    //     weightOutdoor: 68,
    //     inverter: false,
    //     wifi: true,
    //   },
    // },
  },
  {
    title: "Настенно-потолочный кондиционер Shuft SCD-180",
    description: "Гибкая установка: настенный или потолочный монтаж.",
    brand: Brands.SHUFT,
    serie: "Eco",
    images: ["/uploads/shuft1.png"],
    price: 73500,
    stock: Stock.IN_STOCK,
    type: Type.AIR_CONDITIONER,
    typeOf: TypeOf.WALL_CEILING_CONDITIONER,
    href: "/products/shuft-scd180",
    groupId: "SHUFT-ECO-180",
    // airConditionerStat: {
    //   create: {
    //     coolingCapacity: 7.1,
    //     heatingCapacity: 7.3,
    //     areaCoverage: 70,
    //     energyEfficiency: "A+",
    //     noiseLevelIndoor: 31,
    //     noiseLevelOutdoor: 57,
    //     powerConsumption: 2.6,
    //     refrigerantType: "R32",
    //     dimensionsIndoor: "1060×235×675",
    //     dimensionsOutdoor: "900×860×400",
    //     weightIndoor: 30,
    //     weightOutdoor: 62,
    //     inverter: true,
    //     wifi: false,
    //   },
    // },
  },
  {
    title: "Настенно-потолочный кондиционер Shuft SCD-2000",
    description: "Круто! Настенный или потолочный монтаж.",
    brand: Brands.SHUFT,
    serie: "Eco",
    images: ["/uploads/shuft1.png"],
    price: 73500,
    stock: Stock.IN_STOCK,
    type: Type.AIR_CONDITIONER,
    typeOf: TypeOf.WALL_CEILING_CONDITIONER,
    href: "/products/shuft-scd2000",
    groupId: "SHUFT-ECO-180",
    // airConditionerStat: {
    //   create: {
    //     coolingCapacity: 7.1,
    //     heatingCapacity: 7.3,
    //     areaCoverage: 70,
    //     energyEfficiency: "A+",
    //     noiseLevelIndoor: 31,
    //     noiseLevelOutdoor: 57,
    //     powerConsumption: 2.6,
    //     refrigerantType: "R32",
    //     dimensionsIndoor: "1060×235×675",
    //     dimensionsOutdoor: "900×860×400",
    //     weightIndoor: 30,
    //     weightOutdoor: 62,
    //     inverter: true,
    //     wifi: false,
    //   },
    // },
  },
  {
    title: "Сплит-система TCL Elite T09H",
    description: "Тихая работа и Wi-Fi управление.",
    brand: Brands.TCL,
    serie: "Elite",
    images: ["/uploads/tcl1.png"],
    price: 41500,
    stock: Stock.OUT_OF_STOCK,
    type: Type.AIR_CONDITIONER,
    typeOf: TypeOf.WALL_MOUNTED_AIR,
    href: "/products/tcl-elite-t09h",
    groupId: "TCL-ELITE-09",
    // airConditionerStat: {
    //   create: {
    //     coolingCapacity: 2.6,
    //     heatingCapacity: 2.8,
    //     areaCoverage: 25,
    //     energyEfficiency: "A++",
    //     noiseLevelIndoor: 22,
    //     noiseLevelOutdoor: 50,
    //     powerConsumption: 0.9,
    //     refrigerantType: "R32",
    //     dimensionsIndoor: "715×285×194",
    //     dimensionsOutdoor: "700×550×270",
    //     weightIndoor: 8.0,
    //     weightOutdoor: 25.0,
    //     inverter: true,
    //     wifi: true,
    //   },
    // },
  },
  {
    title: "Сплит-система Ishimatsu ICV-24HRN",
    description: "Надежная система с расширенным сроком службы.",
    brand: Brands.ISHIMATSU,
    serie: "Comfort",
    images: ["/uploads/ishi1.png"],
    price: 59990,
    stock: Stock.PRE_ORDER,
    type: Type.AIR_CONDITIONER,
    typeOf: TypeOf.WALL_MOUNTED_AIR,
    href: "/products/ishimatsu-icv24hrn",
    groupId: "ISHIMATSU-COMFORT-24",
    // airConditionerStat: {
    //   create: {
    //     coolingCapacity: 7.0,
    //     heatingCapacity: 7.4,
    //     areaCoverage: 65,
    //     energyEfficiency: "A+",
    //     noiseLevelIndoor: 28,
    //     noiseLevelOutdoor: 54,
    //     powerConsumption: 2.3,
    //     refrigerantType: "R32",
    //     dimensionsIndoor: "890×290×210",
    //     dimensionsOutdoor: "860×640×310",
    //     weightIndoor: 11,
    //     weightOutdoor: 35,
    //     inverter: true,
    //     wifi: false,
    //   },
    // },
  },
  {
    title: "Кассетный кондиционер Biryusa BRC-60K",
    description: "Эффективное охлаждение для кафе и ресторанов.",
    brand: Brands.BIRYUSA,
    serie: "Standard",
    images: ["/uploads/biryusa1.png"],
    price: 88500,
    stock: Stock.IN_STOCK,
    type: Type.AIR_CONDITIONER,
    typeOf: TypeOf.CASSETE_CONDITIONER,
    href: "/products/biryusa-brc60k",
    groupId: "BIRYUSA-STAND-60",
    // airConditionerStat: {
    //   create: {
    //     coolingCapacity: 6.5,
    //     heatingCapacity: 6.8,
    //     areaCoverage: 60,
    //     energyEfficiency: "A",
    //     noiseLevelIndoor: 30,
    //     noiseLevelOutdoor: 55,
    //     powerConsumption: 2.4,
    //     refrigerantType: "R410A",
    //     dimensionsIndoor: "850×300×850",
    //     dimensionsOutdoor: "900×650×350",
    //     weightIndoor: 24,
    //     weightOutdoor: 49,
    //     inverter: false,
    //     wifi: false,
    //   },
    // },
  },
  {
    title: "Канальный кондиционер Dahaci DHC-90",
    description: "Высокая производительность для больших залов.",
    brand: Brands.DAHACI,
    serie: "Ultra",
    images: ["/uploads/dahaci1.png"],
    price: 158000,
    stock: Stock.PRE_ORDER,
    type: Type.AIR_CONDITIONER,
    typeOf: TypeOf.DUCTED_CONDITIONER,
    href: "/products/dahaci-dhc90",
    groupId: "DAHACI-ULTRA-90",
    // airConditionerStat: {
    //   create: {
    //     coolingCapacity: 12.0,
    //     heatingCapacity: 12.5,
    //     areaCoverage: 120,
    //     energyEfficiency: "A",
    //     noiseLevelIndoor: 38,
    //     noiseLevelOutdoor: 60,
    //     powerConsumption: 4.2,
    //     refrigerantType: "R32",
    //     dimensionsIndoor: "1400×320×750",
    //     dimensionsOutdoor: "1100×940×420",
    //     weightIndoor: 42,
    //     weightOutdoor: 75,
    //     inverter: true,
    //     wifi: true,
    //   },
    // },
  },
  {
    title: "Настенно-потолочный кондиционер Belluna BL-50W",
    description: "Современный дизайн и широкий функционал.",
    brand: Brands.BELLUNA,
    serie: "Smart",
    images: ["/uploads/belluna1.png"],
    price: 102000,
    stock: Stock.IN_STOCK,
    type: Type.AIR_CONDITIONER,
    typeOf: TypeOf.WALL_CEILING_CONDITIONER,
    href: "/products/belluna-bl50w",
    groupId: "BELLUNA-SMART-50",
    // airConditionerStat: {
    //   create: {
    //     coolingCapacity: 5.2,
    //     heatingCapacity: 5.5,
    //     areaCoverage: 50,
    //     energyEfficiency: "A+",
    //     noiseLevelIndoor: 27,
    //     noiseLevelOutdoor: 53,
    //     powerConsumption: 1.9,
    //     refrigerantType: "R410A",
    //     dimensionsIndoor: "960×240×680",
    //     dimensionsOutdoor: "870×860×360",
    //     weightIndoor: 28,
    //     weightOutdoor: 58,
    //     inverter: true,
    //     wifi: true,
    //   },
    // },
  },

  // Оказывается createMany не поддерживает вложенные модели, пришлось их закоментить
];
